#nullable enable
using System;
using System.Collections.Generic;
using UnityEngine;

namespace Metin2.Frontend.Proto
{
    /// <summary>
    /// Client-side presentation data for one item (item_proto → Unity).
    /// Numeric fields are presentation-only: prices, stats and upgrade
    /// authority stays on the server (AGENT_DEVELOPMENT_GUIDE §7.4).
    /// Generated by ProtoImporter from the converter JSON; embeds
    /// copyrighted name strings → the generated assets live under
    /// Assets/Resources/GameData (local-only, ADR-0003).
    /// </summary>
    [Serializable]
    public sealed class ItemDef
    {
        public long Vnum;
        public string LocaleName = "";
        public long Type;
        public long SubType;
        public long Weight;
        public long Size;
        public long AntiFlags;
        public long Flags;
        public long WearFlags;
        public long ImmuneFlag;
        public long Gold;
        public long ShopBuyPrice;
        public long RefinedVnum;
        public long RefineSet;
        public long[] Values = Array.Empty<long>();
        public long[] Sockets = Array.Empty<long>();
        public string IconPath = "";

        /// <summary>Icon sprite link (local-only asset, ADR-0003).</summary>
        public Sprite? Icon;
    }

    /// <summary>
    /// Client-side presentation data for one mob/NPC (mob_proto → Unity).
    /// szFolder is the model folder name for the future GR2 pipeline
    /// (RaceManager.cpp:30-92). Same authority rule as ItemDef.
    /// </summary>
    [Serializable]
    public sealed class MobDef
    {
        public long Vnum;
        public string LocaleName = "";
        public long Type;
        public long Rank;
        public long BattleType;
        public long Level;
        public long Size;
        public long MaxHp;
        public long Exp;
        public long GoldMin;
        public long GoldMax;
        public long DamageMin;
        public long DamageMax;
        public long Def;
        public long AttackSpeed;
        public long MovingSpeed;
        public string Folder = "";
    }

    /// <summary>
    /// Item catalog database (generated, local-only). Lookups are lazy —
    /// the dictionary is rebuilt on first access after domain reload.
    /// </summary>
    public sealed class ItemDatabase : ScriptableObject
    {
        public ItemDef[] Items = Array.Empty<ItemDef>();

        private Dictionary<long, ItemDef>? _byVnum;

        public int Count => Items.Length;

        public ItemDef? Find(long vnum)
        {
            if (_byVnum == null)
            {
                _byVnum = new Dictionary<long, ItemDef>(Items.Length);
                foreach (ItemDef item in Items)
                {
                    _byVnum[item.Vnum] = item;
                }
            }

            return _byVnum.TryGetValue(vnum, out ItemDef? item2) ? item2 : null;
        }
    }

    /// <summary>Mob/NPC catalog database (generated, local-only).</summary>
    public sealed class MobDatabase : ScriptableObject
    {
        public MobDef[] Mobs = Array.Empty<MobDef>();

        private Dictionary<long, MobDef>? _byVnum;

        public int Count => Mobs.Length;

        public MobDef? Find(long vnum)
        {
            if (_byVnum == null)
            {
                _byVnum = new Dictionary<long, MobDef>(Mobs.Length);
                foreach (MobDef mob in Mobs)
                {
                    _byVnum[mob.Vnum] = mob;
                }
            }

            return _byVnum.TryGetValue(vnum, out MobDef? mob2) ? mob2 : null;
        }
    }
}
